export const AUTHENTICATED = 'AUTHENTICATED';
export const ACCOUNT_REMOVED = 'ACCOUNT_REMOVED';
export const MENU_OPEN = 'MENU_OPEN';
export const LOG_OUT = 'LOG_OUT';
export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM';
export const JOINED_ROOM = 'JOINED_ROOM';
export const LEAVED_ROOM = 'LEAVED_ROOM';
export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const OPEN_INFO_ALERT = 'OPEN_INFO_ALERT';
export const ROOM_CREATED_NOW = 'ROOM_CREATED_NOW';
export const NEW_USER_JOIN = 'NEW_USER_JOIN';
export const USER_LEFT = 'USER_LEFT';
export const MESSAGE = 'MESSAGE';
export const REMOVE_INTERNAL_MESSAGE = 'REMOVE_INTERNAL_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const REMOVE_GROUP_MESSAGES = 'REMOVE_GROUP_MESSAGES';
export const JOINED_ROOM_ID = 'JOINED_ROOM_ID';
export const MESSAGE_DOWNLOAD_PROGRESS = 'MESSAGE_DOWNLOAD_PROGRESS';
export const ALTER_MESSAGE_PAYLOAD = 'ALTER_MESSAGE_PAYLOAD';
export const MEDIA_SOURCE_ADDED = 'MEDIA_SOURCE_ADDED';
export const REMOVE_SINGLE_MEDIA_SOURCE = 'REMOVE_SINGLE_MEDIA_SOURCE';
export const REMOVE_MEDIA_SOURCES = 'REMOVE_MEDIA_SOURCES';
export const MAXIMIZE_MEDIA_SOURCE = 'MAXIMIZE_MEDIA_SOURCE';

export const MESSENGER_RIGHT_CHANGE_STATE = 'MESSENGER_RIGHT_CHANGE_STATE';
export const OPEN_CLOSE_FULL_SCREEN = 'OPEN_CLOSE_FULL_SCREEN';

